/* Darshan site v2 — strings. pt-BR lives inline in the DC (default paint);
   en loads here. NFR-009: pt+en at launch. Quotations stay canonical. */
window.__darshanSiteStrings = {
  en: {
    nav: ['entry', 'the path', 'the library', 'the dana', 'integrity', 'questions'],
    tagline: 'to see, and be seen, by the sacred',
    qtrans: [
      'Thou hast a right to action, but only to action, never to its fruits.',
      'All this is for habitation by the Lord — each individual universe of movement in the universal motion.',
    ],
    qcite: [
      'Bhagavad Gita, II.47 · tr. Sri Aurobindo',
      'Isha Upanishad, mantra 1 · tr. Sri Aurobindo',
    ],
    openCta: 'open in context',
    p1: 'A digital darshan, not a chatbot — the contemplative interface of the Aadi Yogi wisdom engine.',
    p2: 'Upanishads, Gita, Tirumandiram, Sri Aurobindo, the Mother — served with silence, citation and rhythm. Never as a feed.',
    p3: 'Free, anonymous, offline where it matters. Built to be left in peace.',
    enter: 'enter the app',
    traits: 'free · anonymous · offline',
    walkLabel: 'the path',
    walkIntro: 'nine gestures, walked as stations — one per visit, and a way to leave in peace.',
    walk: [
      { name: 'the threshold', skt: 'dvāra', line: 'one breath before anything opens.' },
      { name: 'the court', skt: '', line: 'one calm court; one gesture at a time.' },
      { name: 'the word', skt: 'vāk darshan', line: 'one passage a day, offered alone.' },
      { name: 'the inquiry', skt: 'praśna', line: 'a well, not a slot machine — cited answers, sometimes silence.' },
      { name: 'living maps', skt: 'mārga', line: 'inner crossings, station by station.' },
      { name: 'the practice field', skt: 'sādhana', line: 'silence, offering, the evening look-back, japa.' },
      { name: 'the library', skt: 'svādhyāya', line: 'reading rooms with full provenance.' },
      { name: 'the sky map', skt: 'ṛtu', line: 'the real sky, read as rhythm — never as fate.' },
      { name: 'the house of nature', skt: 'prakṛti', line: 'elements, land, the body as temple — reading, never prescription.' },
      { name: 'the silence room', skt: 'mauna', line: 'nothing. one slow pulse, zero telemetry.' },
    ],
    hidden: 'and one hidden room — the inner diary (sākṣī), written for no one.',
    libLabel: 'the library',
    libIntro: 'the traditions of the corpus, with provenance and state.',
    shelves: [
      { name: 'the Vedas', line: 'the root chant — hymns to fire, dawn, the vast.' },
      { name: 'the Upanishads', line: 'sitting close: being itself, questioned directly.' },
      { name: 'the Bhagavad Gita', line: 'the battlefield as the inner field.' },
      { name: 'the Puranas', line: 'the old stories that carry the dharma.' },
      { name: 'the Tantras', line: 'body and cosmos as one fabric.' },
      { name: 'the Siddhas · Tirumandiram', line: 'the Tamil singers of the body-temple.' },
      { name: 'Sri Aurobindo', line: 'the evolution of consciousness, written from within.' },
      { name: 'the Mother', line: 'practice, recorded day by day.' },
    ],
    states: { open: 'open', arriving: 'arriving', future: 'future' },
    officialLabel: 'official source ↗',
    danaLabel: 'the dana',
    danaLaw: 'The wisdom is free. You may pay, if you wish, for the machine\u2019s time and for other people\u2019s access.',
    danaCards: [
      { name: 'free, forever', line: 'every surface with no cost per use — for everyone, without an account.' },
      { name: 'the machine\u2019s time', line: 'the inquiry has a free daily measure. beyond it, credits at cost.' },
      { name: 'dana', line: 'one quiet offering page. it funds the free measure of others.' },
    ],
    freeChips: ['the word', 'the library', 'the silence', 'the practice', 'the maps', 'the sky', 'the diary'],
    meterLabel: 'free daily measure',
    price: '≈ R$ 0.10 / answer',
    priceNote: 'anchored to real cost; shown before each use. pix · card.',
    offerTitle: 'offering',
    otherLabel: 'other',
    freqOnce: 'once',
    freqMonthly: 'monthly',
    methodPix: 'pix',
    methodCard: 'card',
    offerBtn: 'offer',
    offerDone: 'received. the well stays open.',
    offerAgain: 'new offering',
    offerNote: 'never a popup. it never changes how the app behaves.',
    neverLine: 'never — ads · sale of data · content-locking subscription · urgency · guilt',
    intLabel: 'lineage & integrity',
    intRows: [
      { name: 'resolvable citations', line: 'every line navigates to the book — integrity 1.0 in CI.', doc: 'docs/passage_id_scheme.md' },
      { name: 'copyright honored', line: 'restricted works point to the official source.', doc: 'docs/decisions/0004-editorial-policy.md' },
      { name: 'anti-prophecy', line: 'rhythm, never fate — no natal charts, no predictions.', doc: 'docs/decisions/0002-natal-boundary-strict.md' },
      { name: 'health fence', line: 'heritage cited as documentary reading, never prescription.', doc: 'docs/decisions/0003-health-gate-interim.md' },
      { name: 'privacy by architecture', line: 'anonymous by default; the diary is local and encrypted.', doc: 'docs/skyforge/darshan/nfr.yaml' },
      { name: 'presence, not engagement', line: 'presence metrics published; screen-time never optimized.', doc: 'docs/darshan_interface_concept.md' },
    ],
    faqLabel: 'sincere questions',
    faq: [
      { q: 'does this replace a guru?', a: 'no. the instrument never simulates a teacher — and points away from itself.' },
      { q: 'is it therapy?', a: 'no. in crisis it restrains itself and points to qualified care.' },
      { q: 'why is it free?', a: 'dana. the dharma of these lineages always moved by gift, never by toll.' },
      { q: 'my data?', a: 'local and encrypted. anonymous by default; nothing is ever sold.' },
      { q: 'can I trust the citations?', a: 'every claim navigates to the book — integrity 1.0, verified in CI.' },
    ],
    footerSources: 'sources · the Upanishads · the Bhagavad Gita · the Vedas · the Puranas · the Tantras · the Tirumandiram · Sri Aurobindo · the Mother',
    footerLangs: 'português · english — quotations stay in their canonical language',
    footerGo: 'go gently.',
  },
};
